### ISSUE TITLE
Tapping "Today" button doesn't do anything when viewing previous months

### ISSUE THREAD

**Issue by deffs** [rwbr/flutter_neat_and_clean_calendar#69] opened 2024-01-08 17:33 UTC
When using the calendar and toggling to previous months the "Today" button above the month name doesn't work properly as no navigation to the current date happens. I.e. current month is January then toggling back to December and tapping "Today" doesn't do anything (calendar freezes). Toggling to future months and tapping "Today" works properly.

**Comment by rwbr** [comment] 2024-01-09 08:35
I can't reproduce this problem. You need to give me more context to understand your problem.

If I run the example app of the package, it works as expected.
![Tapping-Today-Button](https://github.com/rwbr/flutter_neat_and_clean_calendar/assets/144948/13a0e674-3502-4b31-93df-3a569488ff80)

Are you using the example? Can you reproduce your problem with the example app?

**Comment by deffs** [comment] 2024-01-09 16:13
Looks like this is due to me not setting `onMonthChanged` in my Calendar definition. If I delete the `onMonthChanged` property from my declaration or I set it as `null` it throws an exception when I go to previous months and tap the "Today" button. If I set it to `(value) {}` it works fine. 

Same issue with `onDateSelected`. When trying to tap on a date in a future month.

This is the workaround that works for me:

<img width="196" alt="image" src="https://github.com/rwbr/flutter_neat_and_clean_calendar/assets/26584313/9e150c4b-fc35-4b57-8a98-61317e4e3130">

**Comment by rwbr** [comment] 2024-01-09 17:13
Ok, I understand. Thank you. I'll find a way to fix this.

**Comment by rwbr** [comment] 2024-01-11 08:35
I can't reproduce this problem in the example app. Even when I set these callback parameters to `null`, everything works as expected. Did you try this in the example? What's the difference between the example and your code?

**Comment by rwbr** [comment] 2024-08-06 13:49
I have no idea, what goes wrong there. I close this one

**Closed by rwbr** 2024-08-06 13:49 UTC
Labels: question, feedback-requested
